var annotated_dup =
[
    [ "Apartamento", "class_apartamento.html", "class_apartamento" ],
    [ "BinaryNode", "class_binary_node.html", "class_binary_node" ],
    [ "BST", "class_b_s_t.html", "class_b_s_t" ],
    [ "BSTItrIn", "class_b_s_t_itr_in.html", "class_b_s_t_itr_in" ],
    [ "BSTItrLevel", "class_b_s_t_itr_level.html", "class_b_s_t_itr_level" ],
    [ "BSTItrPost", "class_b_s_t_itr_post.html", "class_b_s_t_itr_post" ],
    [ "BSTItrPre", "class_b_s_t_itr_pre.html", "class_b_s_t_itr_pre" ],
    [ "Condominio", "class_condominio.html", "class_condominio" ],
    [ "Condomino", "class_condomino.html", "class_condomino" ],
    [ "CondominoDuplicado", "class_condomino_duplicado.html", "class_condomino_duplicado" ],
    [ "DadosInvalidos", "class_dados_invalidos.html", "class_dados_invalidos" ],
    [ "funcHash", "structfunc_hash.html", "structfunc_hash" ],
    [ "Funcionario", "class_funcionario.html", "class_funcionario" ],
    [ "Habitacao", "class_habitacao.html", "class_habitacao" ],
    [ "Main", "class_main.html", "class_main" ],
    [ "NomeUtilizadorIndisponivel", "class_nome_utilizador_indisponivel.html", "class_nome_utilizador_indisponivel" ],
    [ "NomeUtilizadorInvalido", "class_nome_utilizador_invalido.html", "class_nome_utilizador_invalido" ],
    [ "Paragem", "class_paragem.html", "class_paragem" ],
    [ "PasswordInvalida", "class_password_invalida.html", "class_password_invalida" ],
    [ "Posicao", "struct_posicao.html", "struct_posicao" ],
    [ "Servico", "class_servico.html", "class_servico" ],
    [ "Transporte", "class_transporte.html", "class_transporte" ],
    [ "UtilizadorPasswordEspacos", "class_utilizador_password_espacos.html", "class_utilizador_password_espacos" ],
    [ "Vivenda", "class_vivenda.html", "class_vivenda" ]
];